### ISSUE TITLE
Azure Devops

### ISSUE THREAD

**Issue by howardjones** [hyper-expanse/parse-repository-url#33]
Hi,

I'd like to add Azure Devops recognition to your library, so I can use `standard-version` with my project. Is that something you are open to? I'm not really a javascript developer, but I know my way around a bit, and around regexps!

**Comment by hutson** [comment]
@howardjones our project scope is describe here - https://github.com/hyper-expanse/parse-repository-url/blob/master/contributing.md#project-scope (I just added it :smile: )

Basically, if it's a valid `git` URL, then this repository should be able to parse the URL and break it down into its component parts, such as user/organization, project, host, etc.

**Comment by hutson** [comment]
Unfortunately I have not had the time to properly investigate and address support requests related to this package. This reflects directly on my inability to allocate the time this project requires to make it available and useful to the community. As a result, and to avoid users from depending on an unsupported project, I am moving forward with deprecating the package on the NPM registry and archiving this repository. Please consider migrating to another supported library.
