### ISSUE TITLE
Not able to specify custom format

### ISSUE THREAD

**Issue by uxkjaer** [hyper-expanse/parse-repository-url#35]
We have issued using standard-version as we use a self-hosted gitlab with groups and sub-groups, but no user defined repositories. 

I've created a [pull request](https://github.com/hyper-expanse/parse-repository-url/pull/34) that adds a formatting capability which can be defined in the package.json file

**Comment by hutson** [comment]
@uxkjaer I have posted a comment upstream - https://github.com/conventional-changelog/standard-version/issues/525#issuecomment-695830030

I am not entirely sure why the current output of `@hutson/parse-repository-url` is causing `standard-version` to generate invalid URLs in the changelog output.

I would like to better understand the expectations of `standard-version` before making changes to the interface of `@hutson/parse-repository-url`.

**Comment by hutson** [comment]
Unfortunately I have not had the time to properly investigate and address support requests related to this package. This reflects directly on my inability to allocate the time this project requires to make it available and useful to the community. As a result, and to avoid users from depending on an unsupported project, I am moving forward with deprecating the package on the NPM registry and archiving this repository. Please consider migrating to another supported library.
